import os
Import('env')
Import('src_objs')

include_paths = ['.']
env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )

cxx_sources = Glob('*.cxx')
c_sources = Glob('*.c')

src_objs += [ env.Object(s) for s in cxx_sources ] + [ env.Object(s) for s in c_sources ]
